"""
The design step on the ESSENTIAL 4-dimensional quotient.

recession.py establishes, exactly over Q(n), that the design problem carries a
FOUR-dimensional lineality space -- generated by sigma_0 Gram += mu J and
sigma_11 Gram += 1 v^T + v 1^T for v constant on the three Stab((0,0)) classes
K, R u C, I -- and that its four generators have an invertible 4 x 4 minor on the
four free lambda columns f15, f16, f17, f18.  So

    {f15 = f16 = f17 = f18 = 0}

is a transversal slice, and the design has only FOUR essential unknowns:
f6, f9, f11, f12.  On that slice the feasible set has trivial recession cone,
hence is COMPACT, which is exactly what the drifting optima of design_sdp.py
lacked.

The eight quantities that live on the quotient are

    theta_1, theta_2, B, D, the two leading minors of C,
    and the two leading minors of T^T A T,   T spanning s^perp,
    s = (1, 2(n-1), (n-1)^2).

The remaining two conditions, theta_0 > 0 and A > 0, are NOT constraints at all:
they are fixed afterwards by the gauge, in closed form.  Write e = (1,0,0), which
satisfies s^T e = 1.  Moving along the lineality space adds mu n^2 to theta_0 and
s w^T + w s^T to A, with w free in R^3; in the basis (e, T) that added matrix is
[[2 w_1, (T^T w)^T], [T^T w, 0]].  So choosing

    T^T w = -T^T A e ,      w_1 = (gamma - A_11)/2 ,      mu = (tau - theta_0)/n^2

makes A block-diagonal, equal to diag(gamma, T^T A T) in the basis (e, T), and
sets theta_0 = tau.  Take gamma = tau = 1.  Then A > 0 exactly when T^T A T > 0,
which is already one of the eight, and theta_0 = 1 > 0.

So the whole k = 3 design reduces to four rational functions of n making eight
explicit rational functions of n positive on n >= 4 -- and the gauge, which is a
formula, supplies the rest.
"""

import os
import sys
from fractions import Fraction as F

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "dittert"))
sys.path.insert(0, HERE)
import blocks as bl                                              # noqa: E402
import fit_curve as fc                                           # noqa: E402
import general_k3 as g                                           # noqa: E402
import reduced as rd                                             # noqa: E402

FREE = fc.FREE
NFREE = fc.NFREE
IDX = fc.IDX
ESS = [6, 9, 11, 12]                       # the essential free columns
ESS_I = [FREE.index(c) for c in ESS]
GAUGE = [15, 16, 17, 18]                   # the free lambda columns
GAUGE_I = [FREE.index(c) for c in GAUGE]
NAMES = ["G0.theta1", "G0.theta2", "H.B", "H.D",
         "H.C minor1", "H.C minor2", "TAT minor1", "TAT minor2"]


def free_from_alpha(alpha, n, E=3):
    """f6, f9, f11, f12 = alpha/n^E; the four gauge coordinates zero."""
    x = [F(0)] * NFREE
    for a, i in zip(alpha, ESS_I):
        x[i] = F(a) / F(n) ** E
    return x


def hard_at(alpha, n, E=3):
    return rd.hard_quantities(n, free_from_alpha(alpha, n, E))


# ------------------------------------------------------------------ diagnostics
def scaling_report(alpha, ns=(10, 100, 1000)):
    """How each of the eight quantities scales in n at a fixed alpha."""
    print("  quantity        " + "".join(f"{n:>14d}" for n in ns) + "    exponent")
    vals = {nm: [] for nm in NAMES}
    for n in ns:
        for nm, v in hard_at(alpha, n):
            vals[nm].append(float(v))
    for nm in NAMES:
        v = vals[nm]
        e = None
        if v[0] and v[-1] and v[0] * v[-1] > 0:
            e = np.log(abs(v[-1] / v[0])) / np.log(ns[-1] / ns[0])
        print(f"  {nm:<14s}" + "".join(f"{x:14.4e}" for x in v)
              + (f"    n^{e:+.2f}" if e is not None else "    (sign change)"))
    return vals


# ------------------------------------------------------------------- the SDP
def sbasis(n, D):
    """
    The ansatz basis.  Put s = m/n = 1 - 4/n, which runs over [0, 1) as n runs
    over [4, infinity), and take

        f_c = ( sum_j w_j s^j ) / n^3 .

    This spans exactly the same functions as u_c(m)/n^{D+3} with deg u_c <= D
    (the change of basis is triangular), but the coefficients are O(1) and the
    variable is bounded, so the fit is well conditioned.  Keeping E = D + 3 is
    what preserves the measured leading order f_c ~ const/n^3; letting E and D
    move independently changes the asymptotics and makes the fit chase the wrong
    limit.
    """
    s = 1.0 - 4.0 / float(n)
    return np.array([s ** j for j in range(D + 1)]) / float(n) ** 3


def solve_alpha(ns, D=0, cap=1e6, verbose=True, E=None, scales=None):
    """
    Maximise the least normalised margin over one curve valid at every n in ns.
    """
    import cvxpy as cp
    u = cp.Variable((4, D + 1))
    t = cp.Variable()
    cons = [t <= cap]
    for n in ns:
        s = 1.0 - 4.0 / float(n)
        b = u @ np.array([s ** j for j in range(D + 1)])     # beta = f * n^3
        q1, q2, qB, qD, Cm, Tm = rd.normalised_forms_exact(n, b)
        cons += [q1 >= t, q2 >= t, qB >= t, qD >= t,
                 Cm - t * np.eye(2) >> 0, Tm - t * np.eye(2) >> 0]
    prob = cp.Problem(cp.Maximize(t), cons)
    for solver in ("CLARABEL", "SCS"):
        try:
            prob.solve(solver=getattr(cp, solver), verbose=False)
            if prob.status in ("optimal", "optimal_inaccurate"):
                if verbose:
                    print(f"    D={D}: {prob.status}, t = {t.value:.6g}")
                return np.array(u.value, dtype=float).reshape(4, D + 1), \
                    float(t.value)
        except Exception as exc:                                 # noqa: BLE001
            if verbose:
                print(f"    {solver} failed: {exc}")
    return None, None


def solve_alpha_ref(ns, D, refs, cap=10.0, verbose=False):
    """
    One curve for every n in ns, with the margin measured RELATIVE to the
    analytic centre at that same n.  t = 1 would mean the curve is as well
    centred as the centre itself; t > 0 means strictly feasible.
    """
    import cvxpy as cp
    u = cp.Variable((4, D + 1))
    t = cp.Variable()
    cons = [t <= cap]
    for n in ns:
        s = 1.0 - 4.0 / float(n)
        b = u @ np.array([s ** j for j in range(D + 1)])
        q1, q2, qB, qD, Cm, Tm = rd.normalised_forms_exact(n, b)
        r = refs[n]
        cons += [q1 >= t * r["q1"], q2 >= t * r["q2"],
                 qB >= t * r["qB"], qD >= t * r["qD"],
                 Cm - t * r["C"] >> 0, Tm - t * r["T"] >> 0]
    prob = cp.Problem(cp.Maximize(t), cons)
    for solver in ("CLARABEL", "SCS"):
        try:
            prob.solve(solver=getattr(cp, solver), verbose=False)
            if prob.status in ("optimal", "optimal_inaccurate"):
                return np.array(u.value, dtype=float).reshape(4, D + 1), \
                    float(t.value)
        except Exception:                                        # noqa: BLE001
            continue
    return None, None


def rf_free_from_s(wq, D):
    """
    The eight free variables over Q(n) from exact coefficients in the s basis:
    f_c = (sum_j w_j s^j)/n^3 with s = (n-4)/n, so f_c = (sum_j w_j (n-4)^j
    n^{D-j}) / n^{D+3}.
    """
    fs = [g.RF([]) for _ in range(NFREE)]
    den = g.RF([F(0)] * (D + 3) + [F(1)])
    for t, i in enumerate(ESS_I):
        num = []
        for j in range(D + 1):
            if not wq[t][j]:
                continue
            acc = [F(1)]
            for _ in range(j):
                acc = g.pmul(acc, [F(-4), F(1)])          # (n-4)^j
            for _ in range(D - j):
                acc = g.pmul(acc, [F(0), F(1)])           # n^{D-j}
            num = g.padd(num, g.pscale(acc, wq[t][j]))
        fs[i] = g.RF(num) / den
    return fs


# ------------------------------------------------------- the gauge, in closed form
RFONE = g.RF([F(1)])
RFN = g.RF([F(0), F(1)])
LIN = None


def _lineality():
    global LIN
    if LIN is None:
        import recession as rc
        LIN = rc.lineality_free()
    return LIN


def rf_free_from_alpha(uq, E):
    """
    The eight free variables as elements of Q(n), from polynomial numerators uq
    (in m = n - 4) for the four ESSENTIAL coordinates.  Gauge coordinates zero.
    """
    nE = g.RF([F(0)] * E + [F(1)])
    fs = [g.RF([]) for _ in range(NFREE)]
    for t, i in enumerate(ESS_I):
        num, acc = [], [F(1)]
        for j, co in enumerate(uq[t]):
            if j:
                acc = g.pmul(acc, [F(-4), F(1)])
            num = g.padd(num, g.pscale(acc, co))
        fs[i] = g.RF(num) / nE
    return fs


def vals19_rf(fs):
    vals = [None] * 19
    for t, c in enumerate(FREE):
        vals[c] = fs[t]
    for i, c in enumerate(fc.PIV):
        v = fc.RES["b"][i]
        for t, fcol in enumerate(FREE):
            a = fc.RES["A"][i][fcol]
            if a:
                v = v - a * fs[t]
        vals[c] = v
    return vals


def apply_gauge(fs, gamma, tau):
    """
    Add the lineality combination that sets theta_0 = tau and makes the 3x3 A
    block equal diag(gamma, T^T A T) in the basis (e, T), e = (1,0,0).

    Both are pure gauge: the eight essential quantities are unchanged, so this
    step cannot fail and introduces no new positivity requirement.  A > 0 then
    holds exactly when T^T A T > 0, which is already one of the eight.
    """
    vals = vals19_rf(fs)
    a, b, c = vals[0], vals[1], vals[2]
    m = RFN - RFONE
    theta0 = a + b * (RFONE + RFONE) * m + c * m * m
    A, _, _, _ = bl.blocks_rational_generic(RFN, vals[3:14], IDX, one=RFONE)

    two = RFONE + RFONE
    p1 = A[0][1] - A[0][0] * two * m
    p2 = A[0][2] - A[0][0] * m * m
    w1 = (gamma - A[0][0]) / two
    w2 = (g.RF([]) - p1) + w1 * two * m
    w3 = (g.RF([]) - p2) + w1 * m * m
    vK, vR, vI = w1, w2 / (two * m), w3 / (m * m)
    mu = (tau - theta0) / (RFN * RFN)

    L = _lineality()
    out = list(fs)
    for coef, gen in zip((mu, vK, vR, vI), L):
        for t in range(NFREE):
            if gen[t]:
                out[t] = out[t] + coef * gen[t]
    return out


def build(uq, E, gamma=None, tau=None):
    """The full eight free variables over Q(n): essential part plus gauge."""
    gamma = gamma if gamma is not None else RFONE / (RFN * RFN * RFN)
    tau = tau if tau is not None else RFONE / RFN
    return apply_gauge(rf_free_from_alpha(uq, E), gamma, tau)


def build_s(wq, D, gamma=None, tau=None):
    """Same, from exact coefficients in the s = (n-4)/n basis."""
    gamma = gamma if gamma is not None else RFONE / (RFN * RFN * RFN)
    tau = tau if tau is not None else RFONE / RFN
    return apply_gauge(rf_free_from_s(wq, D), gamma, tau)


# ------------------------------------------------------------------- driver
def sturm_report(fs, verbose=True):
    import sturm
    qs = sturm.quantities_rf_from(fs)
    good, bad = [], []
    for name, rf in qs:
        s = sturm.sign_on_n_ge_4(rf.den)
        if s == 0:
            bad.append((name, "denominator not sign-definite"))
            continue
        ok, detail = sturm.positive_on_nonneg(
            sturm.shift_to_m(g.pscale(rf.num, F(s))))
        (good if ok else bad).append((name, detail))
    if verbose:
        for name, detail in good:
            print(f"    POSITIVE  {name:<12s}  {detail}")
        for name, detail in bad:
            print(f"    FAILS     {name:<12s}  {detail}")
    return good, bad


def exact_check(fs, ns):
    bad = []
    for n in ns:
        fv = [f.at(F(n)) for f in fs]
        for nm, v in fc.exact_quantities(n, fv):
            if v <= 0:
                bad.append((n, nm, v))
    return bad


def main():
    print("essential design: 4 unknowns on the slice f15=f16=f17=f18=0\n")
    print("STEP A -- how the eight quantities scale, at a trial alpha")
    scaling_report([F(7, 4), F(7, 8), F(7, 2), F(3, 4)])

    print("\nSTEP B -- the essential optimum at each n (compact feasible set)")
    pts = {}
    for n in (4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 80, 100, 128,
              160, 200, 300, 400, 600, 800):
        xv, t, st = rd.solve_reduced(n)
        if xv is None:
            continue
        pts[n] = xv
        if n in (4, 6, 8, 20, 64, 200, 800):
            print(f"  n={n:4d}  alpha = "
                  + "  ".join(f"{xv[i] * n ** 3: 9.5f}" for i in ESS_I)
                  + f"   t = {t:.4g}")

    ns_grid = [n for n in sorted(pts) if n <= 400]
    print("\nSTEP C -- one alpha curve for all n at once")
    for D in (0, 1, 2, 3):
        u, t = solve_alpha(ns_grid, D=D, E=3, scales=default_scales)
        if u is None:
            print(f"    D={D}: SDP failed")
            continue
        for denom in (1, 2, 4, 8, 12, 24, 48, 100, 1000, 10 ** 4, 10 ** 6):
            uq = [[F(int(round(u[t2][j] * denom)), denom) for j in range(D + 1)]
                  for t2 in range(4)]
            fs = build(uq, 3)
            bad = exact_check(fs, [4, 5, 6, 7, 8, 12, 20, 40, 100, 300])
            if bad:
                continue
            print(f"    D={D} denominator {denom}: exact spot check PASSES")
            print("      alpha = " + ", ".join(
                "(" + " + ".join(f"{uq[i][j]}*m^{j}" for j in range(D + 1))
                + ")" for i in range(4)))
            good, badq = sturm_report(fs)
            print(f"      STURM: {len(good)}/10 positive for all n >= 4")
            if not badq:
                out = os.path.join(HERE, "results", "essential_curve.txt")
                with open(out, "w") as fh:
                    fh.write(repr((3, D, [[str(x) for x in r] for r in uq])))
                print(f"      ALL TEN -- saved to {out}")
                return uq, D
            break
    return None, None


if __name__ == "__main__":
    main()
