"""
THE k = 5 CROSS TERMS, derived and verified.

This is the first instance of Theorem X1 beyond the paper's k = 4.  Layer
d = 5 carries N(5) = 17 cross invariants, in four blocks j = 1, 2, 3, 4 of
sizes 4, 7, 4, 2.  Everything is derived from Theorem X1; nothing is fitted.

Written out, with m = d - j, N = n - j and the abbreviations
    L[r,r'] = (x^or)^T z (y^or')          (the single-edge atom)
    e_2(x) = -mu/2,  e_3(x) = p_3(x)/3    (since e_1(x) = e_1(y) = 0)

  j = 1  (m = 4)   survivors (1,3), (3,1), (2,2), (1,1)
     X_{5,1} =  (n-2)(n-3)(n-4)^2 ( L[1,3] + L[3,1] )
              + (n-3)^2(n-4)^2 L[2,2]
              + (n-2)(n-3)(n-4)^2 ( e_2(x) + e_2(y) ) L[1,1]

  j = 2  (m = 3)   survivors (3,0), (0,3), (2,1), (1,2), (1,0), (0,1), (0,0)
     X_{5,2} = -(n-2)(n-3)(n-4) ( T2[3,0] + T2[0,3] )
               -(n-3)(n-4)^2   ( T2[2,1] + T2[1,2] )
               -[ (n-2)(n-3)(n-4) e_2(x) + (n-3)(n-4)^2 e_2(y) ] T2[1,0]
               -[ (n-3)(n-4)^2 e_2(x) + (n-2)(n-3)(n-4) e_2(y) ] T2[0,1]
               +(n-2)(n-3)(n-4) ( e_3(x) + e_3(y) ) sigma_2(z)

  j = 3  (m = 2)   survivors (2,0), (0,2), (1,1), (0,0)
     X_{5,3} =  (n-3)(n-4) ( T3[2,0] + T3[0,2] ) + (n-4)^2 T3[1,1]
              + (n-3)(n-4) ( e_2(x) + e_2(y) ) (2/3) p_3(z)

  j = 4  (m = 1)   survivors (1,0), (0,1)
     X_{5,4} = -(n-4) ( T4[1,0] + T4[0,1] )

with T_j[r,r'] = Theta_j[r,r'] and Theta_2[0,0] = sigma_2(z) = Q/2,
Theta_3[0,0] = (2/3) p_3(z), Theta_4[0,0] = sigma_4(z) -- the last being
exactly @eq-stab-core4 of the paper, which this module's atom engine
rediscovers independently.

Every coefficient above is checked against kappa() and the whole block against
brute force, over QQ, at n = 5, 6, 7.

Usage:  GUARD_MEM=4G GUARD_CPUS=200% GUARD_THREADS=2 ../guard.sh \
            python3 -u collar_k5.py
"""

import random
import sys
from fractions import Fraction as Fr

from collar_core import (atom_name, cross_brute, cross_general, elem, kappa,
                         rand_split, split, survivors, theta, theta_atoms)
from graded_y_bounds import generic_collar

OUT = []
FAIL = 0


def log(*a):
    s = " ".join(str(x) for x in a)
    print(s)
    OUT.append(s)


def check(name, ok):
    global FAIL
    if not ok:
        FAIL += 1
        log(f"    *** FAIL: {name}")
    return ok


def hand_kappa(n, x, y):
    """The 17 coefficients of layer 5, written out by hand from Theorem X1.

    Hand-written on purpose: if these were generated by kappa() the check
    below would be a tautology.  The point is that a human reading of the
    theorem and the machine's evaluation of it agree."""
    e2x, e2y = elem(x, 2), elem(y, 2)
    e3x, e3y = elem(x, 3), elem(y, 3)
    a, b, c = Fr(n - 2), Fr(n - 3), Fr(n - 4)
    return {
        (1, (1, 3)): a * b * c * c,
        (1, (3, 1)): a * b * c * c,
        (1, (2, 2)): b * b * c * c,
        (1, (1, 1)): a * b * c * c * (e2x + e2y),
        (2, (3, 0)): -a * b * c,
        (2, (0, 3)): -a * b * c,
        (2, (2, 1)): -b * c * c,
        (2, (1, 2)): -b * c * c,
        (2, (1, 0)): -(a * b * c * e2x + b * c * c * e2y),
        (2, (0, 1)): -(b * c * c * e2x + a * b * c * e2y),
        (2, (0, 0)): a * b * c * (e3x + e3y),
        (3, (2, 0)): b * c,
        (3, (0, 2)): b * c,
        (3, (1, 1)): c * c,
        (3, (0, 0)): b * c * (e2x + e2y),
        (4, (1, 0)): -c,
        (4, (0, 1)): -c,
    }


def s1_survivor_list():
    log("SEC 1.  THE SURVIVOR LIST AT d = 5.")
    tot = 0
    for j in range(1, 5):
        s = survivors(j, 5 - j)
        tot += len(s)
        log(f"    j={j}  m={5 - j}  |S| = {len(s):2d}   {s}")
    check("Sec1 seventeen survivors at d = 5", tot == 17)
    log(f"    total {tot}   N(5) = (125 - 35 + 12)/6 = {(125 - 35 + 12) // 6}")
    log("")


def s2_coefficients(rng):
    log("SEC 2.  THE SEVENTEEN COEFFICIENTS, hand-written vs Theorem X1.")
    ok = True
    for n in (7, 9, 12):
        x, y, z = rand_split(n, rng)
        for (j, (r, rp)), val in hand_kappa(n, x, y).items():
            if kappa(x, y, 5, j, r, rp, n) != val:
                ok = False
                log(f"    mismatch n={n} j={j} (r,r')=({r},{rp})")
    check("Sec2 every hand coefficient equals kappa()", ok)
    log(f"    n = 7, 9, 12: all seventeen agree exactly over QQ: {ok}")
    log("")


def s3_against_brute(rng):
    log("SEC 3.  THE WHOLE LAYER, against brute force.")
    log("    X_{5,j} from Theorem X1 must equal the definition,")
    log("    sum_{|S|=|T|=j} per(z[S|T]) sigma_{5-j}(L^(S,T)).")
    for n in (5, 6, 7):
        ok, okhand = True, True
        pts = generic_collar(n, 5, want=2, rng=rng) or []
        pts = [split(A, n) for A in pts] + [rand_split(n, rng) for _ in range(2)]
        for (x, y, z) in pts:
            for j in range(1, 5):
                bf = cross_brute(x, y, z, 5, j, n)
                if cross_general(x, y, z, 5, j, n) != bf:
                    ok = False
                hand = sum(v * theta(x, y, z, j, r, rp, n)
                           for (jj, (r, rp)), v in hand_kappa(n, x, y).items()
                           if jj == j)
                if hand != bf:
                    okhand = False
        check(f"Sec3 Theorem X1 vs brute force n={n}", ok)
        check(f"Sec3 hand table vs brute force n={n}", okhand)
        log(f"    n={n}:  theorem {ok}   hand-written table {okhand}"
            f"   ({len(pts)} points, collar and generic)")
    log("")


def s4_atoms():
    log("SEC 4.  THE SHAPE OF EACH INVARIANT, as decorated-graph atoms.")
    log("    An atom is a bipartite multigraph: one z per edge, one free index")
    log("    per vertex, x/y powers as decorations.  Every degree-1 vertex")
    log("    must be decorated -- an undecorated one is killed by a line sum")
    log("    of z.  <axb|edges|decorations>.")
    for j in range(1, 5):
        for (r, rp) in survivors(j, 5 - j):
            at = theta_atoms(j, r, rp)
            log(f"    Theta_{j}[{r},{rp}]   ({len(at)} atoms)")
            for k2, c in sorted(at.items(),
                                key=lambda kv: (kv[0][0], kv[0][1], kv[0][2])):
                log(f"        {str(c):>6s}  {atom_name(k2)}")
    log("")


def s5_named():
    log("SEC 5.  THE THREE PURE-CENTRED SURVIVORS, named.")
    log("    Theta_j[0,0] = sigma_j(z), so the (0,0) survivors carry the")
    log("    CENTRED core into the cross part, weighted by a line invariant")
    log("    of degree m.  The atom engine reproduces the paper's core")
    log("    expansions with no input from them:")
    for j, want in ((2, "sigma_2 = Q/2"),
                    (3, "sigma_3 = (2/3) p_3"),
                    (4, "sigma_4 = (3/2)p_4 + (1/8)Q^2 + (1/4)Z"
                        " - (3/4)Y_R - (3/4)Y_C")):
        at = theta_atoms(j, 0, 0)
        log(f"    Theta_{j}[0,0]  ->  {want}")
        for k2, c in sorted(at.items(),
                            key=lambda kv: (kv[0][0], kv[0][1], kv[0][2])):
            log(f"        {str(c):>6s}  {atom_name(k2)}")
    log("    The five atoms of Theta_4[0,0] are p_4, Y_R, Y_C, Q^2, Z with")
    log("    coefficients 3/2, -3/4, -3/4, 1/8, 1/4: @eq-stab-core4 verbatim.")
    log("")


def main():
    rng = random.Random(20260731)
    log("=" * 74)
    log("THE k = 5 CROSS TERMS, derived from Theorem X1 and verified")
    log("=" * 74)
    log("")
    s1_survivor_list()
    s2_coefficients(rng)
    s3_against_brute(rng)
    s5_named()
    s4_atoms()
    log("=" * 74)
    log(f"TOTAL FAILURES: {FAIL}")
    log("VERDICT: " + ("ALL CHECKS PASS" if FAIL == 0 else "FAILURES PRESENT"))
    log("=" * 74)
    with open("results/collar_k5.log", "w") as fh:
        fh.write("\n".join(OUT) + "\n")
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
